package types

const (
	StatisticTypeActiveNode                = "active_node"
	StatisticTypeActiveSession             = "active_session"
	StatisticTypeActiveSubscription        = "active_subscription"
	StatisticTypeBandwidthConsumption      = "bandwidth_consumption"
	StatisticTypeEndSession                = "end_session"
	StatisticTypeEndSubscription           = "end_subscription"
	StatisticTypeJoinNode                  = "join_node"
	StatisticTypeSessionDuration           = "session_duration"
	StatisticTypeSessionPayment            = "session_payment"
	StatisticTypeSessionStakingReward      = "session_staking_reward"
	StatisticTypeStartSession              = "start_session"
	StatisticTypeStartSubscription         = "start_subscription"
	StatisticTypeSubscriptionDeposit       = "subscription_deposit"
	StatisticTypeSubscriptionPayment       = "subscription_payment"
	StatisticTypeSubscriptionStakingReward = "subscription_staking_reward"
)

const (
	StatisticMethodAverageActiveNodeCount              = "AverageActiveNodeCount"
	StatisticMethodAverageActiveSessionCount           = "AverageActiveSessionCount"
	StatisticMethodAverageActiveSubscriptionCount      = "AverageActiveSubscriptionCount"
	StatisticMethodAverageEndSessionCount              = "AverageEndSessionCount"
	StatisticMethodAverageEndSubscriptionCount         = "AverageEndSubscriptionCount"
	StatisticMethodAverageJoinNodeCount                = "AverageJoinNodeCount"
	StatisticMethodAverageSessionPayment               = "AverageSessionPayment"
	StatisticMethodAverageSessionStakingReward         = "AverageSessionStakingReward"
	StatisticMethodAverageStartSessionCount            = "AverageStartSessionCount"
	StatisticMethodAverageStartSubscriptionCount       = "AverageStartSubscriptionCount"
	StatisticMethodAverageSubscriptionDeposit          = "AverageSubscriptionDeposit"
	StatisticMethodAverageSubscriptionPayment          = "AverageSubscriptionPayment"
	StatisticMethodAverageSubscriptionStakingReward    = "AverageSubscriptionStakingReward"
	StatisticMethodCurrentNodeCount                    = "CurrentNodeCount"
	StatisticMethodCurrentSessionCount                 = "CurrentSessionCount"
	StatisticMethodCurrentSubscriptionCount            = "CurrentSubscriptionCount"
	StatisticMethodHistoricalActiveNodeCount           = "HistoricalActiveNodeCount"
	StatisticMethodHistoricalActiveSessionCount        = "HistoricalActiveSessionCount"
	StatisticMethodHistoricalActiveSubscriptionCount   = "HistoricalActiveSubscriptionCount"
	StatisticMethodHistoricalBandwidthConsumption      = "HistoricalBandwidthConsumption"
	StatisticMethodHistoricalEndSessionCount           = "HistoricalEndSessionCount"
	StatisticMethodHistoricalEndSubscriptionCount      = "HistoricalEndSubscriptionCount"
	StatisticMethodHistoricalJoinNodeCount             = "HistoricalJoinNodeCount"
	StatisticMethodHistoricalSessionDuration           = "HistoricalSessionDuration"
	StatisticMethodHistoricalSessionPayment            = "HistoricalSessionPayment"
	StatisticMethodHistoricalSessionStakingReward      = "HistoricalSessionStakingReward"
	StatisticMethodHistoricalStartSessionCount         = "HistoricalStartSessionCount"
	StatisticMethodHistoricalStartSubscriptionCount    = "HistoricalStartSubscriptionCount"
	StatisticMethodHistoricalSubscriptionDeposit       = "HistoricalSubscriptionDeposit"
	StatisticMethodHistoricalSubscriptionPayment       = "HistoricalSubscriptionPayment"
	StatisticMethodHistoricalSubscriptionStakingReward = "HistoricalSubscriptionStakingReward"
	StatisticMethodTotalBandwidthConsumption           = "TotalBandwidthConsumption"
	StatisticMethodTotalSessionDuration                = "TotalSessionDuration"
	StatisticMethodTotalSessionPayment                 = "TotalSessionPayment"
	StatisticMethodTotalSessionStakingReward           = "TotalSessionStakingReward"
	StatisticMethodTotalSubscriptionDeposit            = "TotalSubscriptionDeposit"
	StatisticMethodTotalSubscriptionPayment            = "TotalSubscriptionPayment"
	StatisticMethodTotalSubscriptionStakingReward      = "TotalSubscriptionStakingReward"
)
