package types

const (
	TagActiveNode                = "active_node"
	TagActiveSession             = "active_session"
	TagActiveSubscription        = "active_subscription"
	TagBandwidthConsumption      = "bandwidth_consumption"
	TagEndSession                = "end_session"
	TagEndSubscription           = "end_subscription"
	TagJoinNode                  = "join_node"
	TagSessionDuration           = "session_duration"
	TagSessionPayment            = "session_payment"
	TagSessionStakingReward      = "session_staking_reward"
	TagStartSession              = "start_session"
	TagStartSubscription         = "start_subscription"
	TagSubscriptionDeposit       = "subscription_deposit"
	TagSubscriptionPayment       = "subscription_payment"
	TagSubscriptionStakingReward = "subscription_staking_reward"
)

const (
	MethodAverageActiveNodeCount              = "AverageActiveNodeCount"
	MethodAverageActiveSessionCount           = "AverageActiveSessionCount"
	MethodAverageActiveSubscriptionCount      = "AverageActiveSubscriptionCount"
	MethodAverageEndSessionCount              = "AverageEndSessionCount"
	MethodAverageEndSubscriptionCount         = "AverageEndSubscriptionCount"
	MethodAverageJoinNodeCount                = "AverageJoinNodeCount"
	MethodAverageSessionPayment               = "AverageSessionPayment"
	MethodAverageSessionStakingReward         = "AverageSessionStakingReward"
	MethodAverageStartSessionCount            = "AverageStartSessionCount"
	MethodAverageStartSubscriptionCount       = "AverageStartSubscriptionCount"
	MethodAverageSubscriptionDeposit          = "AverageSubscriptionDeposit"
	MethodAverageSubscriptionPayment          = "AverageSubscriptionPayment"
	MethodAverageSubscriptionStakingReward    = "AverageSubscriptionStakingReward"
	MethodCurrentNodeCount                    = "CurrentNodeCount"
	MethodCurrentSessionCount                 = "CurrentSessionCount"
	MethodCurrentSubscriptionCount            = "CurrentSubscriptionCount"
	MethodHistoricalActiveNodeCount           = "HistoricalActiveNodeCount"
	MethodHistoricalActiveSessionCount        = "HistoricalActiveSessionCount"
	MethodHistoricalActiveSubscriptionCount   = "HistoricalActiveSubscriptionCount"
	MethodHistoricalBandwidthConsumption      = "HistoricalBandwidthConsumption"
	MethodHistoricalEndSessionCount           = "HistoricalEndSessionCount"
	MethodHistoricalEndSubscriptionCount      = "HistoricalEndSubscriptionCount"
	MethodHistoricalJoinNodeCount             = "HistoricalJoinNodeCount"
	MethodHistoricalSessionDuration           = "HistoricalSessionDuration"
	MethodHistoricalSessionPayment            = "HistoricalSessionPayment"
	MethodHistoricalSessionStakingReward      = "HistoricalSessionStakingReward"
	MethodHistoricalStartSessionCount         = "HistoricalStartSessionCount"
	MethodHistoricalStartSubscriptionCount    = "HistoricalStartSubscriptionCount"
	MethodHistoricalSubscriptionDeposit       = "HistoricalSubscriptionDeposit"
	MethodHistoricalSubscriptionPayment       = "HistoricalSubscriptionPayment"
	MethodHistoricalSubscriptionStakingReward = "HistoricalSubscriptionStakingReward"
	MethodTotalBandwidthConsumption           = "TotalBandwidthConsumption"
	MethodTotalSessionDuration                = "TotalSessionDuration"
	MethodTotalSessionPayment                 = "TotalSessionPayment"
	MethodTotalSessionStakingReward           = "TotalSessionStakingReward"
	MethodTotalSubscriptionDeposit            = "TotalSubscriptionDeposit"
	MethodTotalSubscriptionPayment            = "TotalSubscriptionPayment"
	MethodTotalSubscriptionStakingReward      = "TotalSubscriptionStakingReward"
)
