package types

const (
	StatisticTypeActiveNode          = "active_node"
	StatisticTypeActiveSession       = "active_session"
	StatisticTypeActiveSubscription  = "active_subscription"
	StatisticTypeBytesPayment        = "bytes_payment"
	StatisticTypeBytesStakingReward  = "bytes_staking_reward"
	StatisticTypeBytesSubscription   = "bytes_subscription"
	StatisticTypeEndSession          = "end_session"
	StatisticTypeEndSubscription     = "end_subscription"
	StatisticTypeHoursPayment        = "hours_payment"
	StatisticTypeHoursStakingReward  = "hours_staking_reward"
	StatisticTypeHoursSubscription   = "hours_subscription"
	StatisticTypePlanPayment         = "plan_payment"
	StatisticTypePlanStakingReward   = "plan_staking_reward"
	StatisticTypePlanSubscription    = "plan_subscription"
	StatisticTypeRegisterNode        = "register_node"
	StatisticTypeSessionBytes        = "session_bytes"
	StatisticTypeSessionDuration     = "session_duration"
	StatisticTypeStartSession        = "start_session"
	StatisticTypeStartSubscription   = "start_subscription"
	StatisticTypeSubscriptionBytes   = "subscription_bytes"
	StatisticTypeSubscriptionDeposit = "subscription_deposit"
	StatisticTypeSubscriptionHours   = "subscription_hours"
	StatisticTypeSubscriptionRefund  = "subscription_refund"
)

const (
	StatisticMethodAverageActiveNodeCount              = "AverageActiveNodeCount"
	StatisticMethodAverageActiveSessionCount           = "AverageActiveSessionCount"
	StatisticMethodAverageActiveSubscriptionCount      = "AverageActiveSubscriptionCount"
	StatisticMethodAverageEndSessionCount              = "AverageEndSessionCount"
	StatisticMethodAverageEndSubscriptionCount         = "AverageEndSubscriptionCount"
	StatisticMethodAverageRegisterNodeCount            = "AverageRegisterNodeCount"
	StatisticMethodAverageSessionPayment               = "AverageSessionPayment"
	StatisticMethodAverageSessionStakingReward         = "AverageSessionStakingReward"
	StatisticMethodAverageStartSessionCount            = "AverageStartSessionCount"
	StatisticMethodAverageStartSubscriptionCount       = "AverageStartSubscriptionCount"
	StatisticMethodAverageSubscriptionDeposit          = "AverageSubscriptionDeposit"
	StatisticMethodAverageSubscriptionPayment          = "AverageSubscriptionPayment"
	StatisticMethodAverageSubscriptionStakingReward    = "AverageSubscriptionStakingReward"
	StatisticMethodCurrentNodeCount                    = "CurrentNodeCount"
	StatisticMethodCurrentSessionCount                 = "CurrentSessionCount"
	StatisticMethodCurrentSubscriptionCount            = "CurrentSubscriptionCount"
	StatisticMethodHistoricalActiveNodeCount           = "HistoricalActiveNodeCount"
	StatisticMethodHistoricalActiveSessionCount        = "HistoricalActiveSessionCount"
	StatisticMethodHistoricalActiveSubscriptionCount   = "HistoricalActiveSubscriptionCount"
	StatisticMethodHistoricalSessionBandwidth          = "HistoricalSessionBandwidth"
	StatisticMethodHistoricalEndSessionCount           = "HistoricalEndSessionCount"
	StatisticMethodHistoricalEndSubscriptionCount      = "HistoricalEndSubscriptionCount"
	StatisticMethodHistoricalRegisterNodeCount         = "HistoricalRegisterNodeCount"
	StatisticMethodHistoricalSessionDuration           = "HistoricalSessionDuration"
	StatisticMethodHistoricalSessionPayment            = "HistoricalSessionPayment"
	StatisticMethodHistoricalSessionStakingReward      = "HistoricalSessionStakingReward"
	StatisticMethodHistoricalStartSessionCount         = "HistoricalStartSessionCount"
	StatisticMethodHistoricalStartSubscriptionCount    = "HistoricalStartSubscriptionCount"
	StatisticMethodHistoricalSubscriptionDeposit       = "HistoricalSubscriptionDeposit"
	StatisticMethodHistoricalSubscriptionPayment       = "HistoricalSubscriptionPayment"
	StatisticMethodHistoricalSubscriptionStakingReward = "HistoricalSubscriptionStakingReward"
	StatisticMethodTotalSessionBandwidth               = "TotalSessionBandwidth"
	StatisticMethodTotalSessionDuration                = "TotalSessionDuration"
	StatisticMethodTotalSessionPayment                 = "TotalSessionPayment"
	StatisticMethodTotalSessionStakingReward           = "TotalSessionStakingReward"
	StatisticMethodTotalSubscriptionDeposit            = "TotalSubscriptionDeposit"
	StatisticMethodTotalSubscriptionPayment            = "TotalSubscriptionPayment"
	StatisticMethodTotalSubscriptionStakingReward      = "TotalSubscriptionStakingReward"
)
